login:
    resource: "@UserBundle/Resources/config/routing/login.xml"
    prefix:   /

transferuj:
    resource: "@TransferujBundle/Resources/config/routing.xml"
    prefix:   /

product:
    resource: "@ProductBundle/Resources/config/routing_product.xml"
    prefix:   /produkt

products:
    resource: "@ProductBundle/Resources/config/routing_products.xml"
    prefix:   /produkty

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: products_list
        permanent: true
